import type { LintResult, SkillResult, CollisionResult, Finding } from '../types.js';

function severityEmoji(severity: Finding['severity']): string {
  switch (severity) {
    case 'error':   return '🔴';
    case 'warning': return '🟡';
    case 'info':    return 'ℹ️';
  }
}

function gradeEmoji(grade: string): string {
  switch (grade) {
    case 'A': return '🟢';
    case 'B': return '🔵';
    case 'C': return '🟡';
    case 'D': return '🟠';
    default:  return '🔴';
  }
}

function renderFindings(findings: Finding[]): string {
  if (findings.length === 0) return '';
  return findings
    .map(
      (f) =>
        `| ${severityEmoji(f.severity)} ${f.severity} | \`${f.code}\` | ${f.message} |`,
    )
    .join('\n');
}

function renderSkill(skill: SkillResult): string {
  const lines: string[] = [];
  lines.push(`\n#### Skill: \`${skill.skillName}\``);

  if (skill.descriptionScore) {
    const s = skill.descriptionScore;
    lines.push('');
    lines.push(
      `**Description score:** ${s.total}/100  ${gradeEmoji(s.grade)} Grade **${s.grade}**`,
    );
    lines.push('');
    lines.push('| Dimension | Score | Max |');
    lines.push('|-----------|------:|----:|');
    lines.push(`| Trigger phrases | ${s.triggerPhraseScore} | 30 |`);
    lines.push(`| Negative boundaries | ${s.negativeBoundaryScore} | 25 |`);
    lines.push(`| Specificity | ${s.specificityScore} | 25 |`);
    lines.push(`| Length & structure | ${s.lengthStructureScore} | 20 |`);

    if (s.improvements.length > 0) {
      lines.push('');
      lines.push('**Suggested improvements:**');
      for (const imp of s.improvements) {
        lines.push(`- ${imp}`);
      }
    }
  }

  if (skill.findings.length > 0) {
    lines.push('');
    lines.push('| Severity | Code | Message |');
    lines.push('|----------|------|---------|');
    lines.push(renderFindings(skill.findings));
  }

  return lines.join('\n');
}

function renderCollision(c: CollisionResult): string {
  const lines: string[] = [
    `- 🟡 **Collision:** \`${c.skillA}\` ↔ \`${c.skillB}\` — overlap ${Math.round(c.overlap * 100)}%`,
  ];
  for (const phrase of c.phrases.slice(0, 3)) {
    lines.push(`  - ${phrase}`);
  }
  return lines.join('\n');
}

export function reportMarkdown(result: LintResult): void {
  const { pluginPath, pluginName, findings, skills, collisions, exitCode } = result;

  const lines: string[] = [];
  lines.push('## plugin-lint Report');
  lines.push('');
  lines.push(`**Plugin:** \`${pluginPath}\`${pluginName ? ` (${pluginName})` : ''}`);
  lines.push('');

  const statusEmoji = exitCode === 0 ? '✅' : '❌';
  const statusText = exitCode === 0 ? 'All checks passed' : 'Issues found';
  lines.push(`**Status:** ${statusEmoji} ${statusText}`);
  lines.push('');

  // Plugin-level findings
  if (findings.length > 0) {
    lines.push('### Plugin Structure');
    lines.push('');
    lines.push('| Severity | Code | Message |');
    lines.push('|----------|------|---------|');
    lines.push(renderFindings(findings));
    lines.push('');
  }

  // Skills
  if (skills.length > 0) {
    lines.push('### Skills');
    for (const skill of skills) {
      lines.push(renderSkill(skill));
    }
    lines.push('');
  }

  // Collisions
  if (collisions.length > 0) {
    lines.push('### Trigger Collisions');
    lines.push('');
    for (const c of collisions) {
      lines.push(renderCollision(c));
    }
    lines.push('');
  }

  // Grade summary
  const skillsWithScores = skills.filter((s) => s.descriptionScore);
  if (skillsWithScores.length > 0) {
    lines.push('### Description Grade Summary');
    lines.push('');
    lines.push('| Skill | Score | Grade |');
    lines.push('|-------|------:|-------|');
    for (const s of skillsWithScores) {
      const sc = s.descriptionScore!;
      lines.push(`| \`${s.skillName}\` | ${sc.total} | ${gradeEmoji(sc.grade)} ${sc.grade} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [plugin-lint](https://github.com/danzus/plugin-lint) — built by [DANZUS Holdings LLC](https://aiagentaudit.dev)*');

  console.log(lines.join('\n'));
}
